[package]
name = "relm4-macros-internal"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
version = "0.5.0-rc.1"
rust-version = "1.63"
readme = "README.md"
license = "Apache-2.0 OR MIT"
description = "An idiomatic GUI library inspired by Elm and based on gtk4-rs"

homepage = "https://relm4.org"
repository = "https://github.com/Relm4/Relm4"
documentation = "https://relm4.org/docs/stable/relm4/"

keywords = ["gui", "gtk", "gtk4", "elm", "view"]
categories = ["gui"]

[features]
default = ["relm4"]

# Generate code for generating formatted output of the 
# widget macro syntax.
format = []

# Without the default "relm4" feature, all imports of gtk will
# be `use gtk;` instead of `use relm4::gtk;` thus making it 
# easier to use this crate without Relm4.
relm4 = []

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits", "visit", "visit-mut"] }