[package]
name = "relm4"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
version = "0.5.0-rc.1"
rust-version = "1.63"
readme = "../README.md"
license = "Apache-2.0 OR MIT"
description = "An idiomatic GUI library inspired by Elm and based on gtk4-rs"

homepage = "https://relm4.org"
repository = "https://github.com/Relm4/Relm4"
documentation = "https://relm4.org/docs/stable/relm4/"

keywords = ["gui", "gtk", "gtk4", "elm"]
categories = ["gui"]

[package.metadata.docs.rs]
all-features = true
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[features]
default = ["macros"]
# The dox feature can be used for building the docs without the dependencies and requires Rust Nightly
dox = ["gtk/dox", "adw/dox", "panel/dox"]
libadwaita = ["adw"]
libpanel = ["panel"]
macros = ["relm4-macros"]

gnome_43 = ["gtk/gnome_43", "adw/v1_2"]
gnome_42 = ["gtk/gnome_42"]

# All features except docs. This is also used in the CI
all = ["macros", "libadwaita", "panel"]

[dependencies]
adw = { version = "0.2", optional = true, package = "libadwaita" }

flume = "0.10.14"
futures = "0.3.25"
fragile = "2.0.0"
gtk = { version = "0.5", package = "gtk4" }
once_cell = "1.16"
panel = { version = "0.1", optional = true, package = "libpanel" }
tokio = { version = "1.23", features = ["rt", "rt-multi-thread", "sync"] }

relm4-macros = { version = "0.5.0-rc.1", path = "../relm4-macros", optional = true }
tracing = "0.1.37"
async-trait = "0.1.59"

[dev-dependencies]
relm4-macros = { path = "../relm4-macros" }
criterion = { version = "0.4", default-features = false }

[[bench]]
name = "stress_test"
harness = false
