[package]
name = "relm4-components"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
version = "0.5.0-rc.1"
description = "An idiomatic GUI library inspired by Elm and based on gtk4-rs"
repository = "https://github.com/Relm4/Relm4"
readme = "README.md"
license = "Apache-2.0 OR MIT"
documentation = "https://relm4.org/docs/stable/relm4_components/"

keywords = ["gui", "gtk", "gtk4"]
categories = ["gui"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
features = ["dox"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[dependencies]
log = "0.4.17"
once_cell = "1.16"
relm4 = { version = "0.5.0-rc.1", path = "../relm4", features = ["macros"] }
tracker = "0.2.0"

[features]
dox = ["relm4/dox"]
